spring:
  application:
    name: JokeAppSpring

jokes:
  files:
    pathToJokeFile: src/main/resources/jokes.json
  externalApi:
    urlToJokeApi:
      urlToAnyCategory: "https://v2.jokeapi.dev/joke/Any"
      urlToSpecificCategory: "https://v2.jokeapi.dev/joke/"

application:
  algorithms:
    roundRobin:
      counter: 0
